#!/usr/bin/env python

# Get a list of users in Zendesk.
#
# Author: Benjamin Roberts <ben.roberts@nesi.org.nz>

import sys,os
import re
import getpass
import json
import requests

progname = os.path.basename(__file__)

website = "nesi.zendesk.com"
headers = { 'Content-Type' : 'application/json' }
preferred_locale = "en-gb"

print "This script requires that you have a so-called default password for Zendesk"
print "(i.e., a different password than your single sign-on password through Tuakiri)."
print "If you do not have such a password or have forgotten it, please visit:"
print ""
print "      https://{0}/access/help".format(website)
print ""
zdmyusername = raw_input("Please enter your Zendesk primary email address: ")
zdmypassword = getpass.getpass("Please enter your Zendesk default password: ")

try:
    users_page = requests.get("https://{0}/api/v2/users.json".format(website), auth=(zdmyusername, zdmypassword))
    users = users_page.json()['users']
except ValueError:
    print "Could not fetch JSON data from which to compile a list of users."
    print "Perhaps your username and/or password was not entered correctly?"
    sys.exit(1)

    for user in users:
        print "{1} ({0})".format(user['id'],user['name'])
