#!/usr/bin/env python

# Get a list of users in Zendesk.
#
# Author: Benjamin Roberts <ben.roberts@nesi.org.nz>

import sys,os
import re
import getpass
import codecs, json
import requests

progname = os.path.basename(__file__)
#sys.stdout = codecs.getwriter('utf8')(sys.stdout)

website = "nesi.zendesk.com"
headers = { 'Content-Type' : 'application/json' }
preferred_locale = "en-gb"

print "This script requires that you have a so-called default password for Zendesk"
print "(i.e., a different password than your single sign-on password through Tuakiri)."
print "If you do not have such a password or have forgotten it, please visit:"
print ""
print "      https://{0}/access/help".format(website)
print ""
zdmyusername = raw_input("Please enter your Zendesk primary email address: ")
zdmypassword = getpass.getpass("Please enter your Zendesk default password: ")

with open('zendesk_users.txt', 'w') as outputfile:
    main_users_url = "https://{0}/api/v2/users.json".format(website)
    users_url = main_users_url
    while users_url:
        try:
            users_page = requests.get(users_url, auth=(zdmyusername, zdmypassword))
        except ValueError:
            print "Could not fetch JSON data from which to compile a list of users."
            print "Perhaps your username and/or password was not entered correctly?"
            sys.exit(1)
        users_page_content = users_page.json()
        for user in users_page_content['users']:
            outputfile.write(u"{1} ({0})\n".format(user['id'],user['name']).encode('utf-8'))
        users_url = users_page_content['next_page']
