#!/usr/bin/env python

# List the sections, by category, in a Zendesk help centre.
#
# Author: Benjamin Roberts <ben.roberts@nesi.org.nz>

import sys,os
import re
import getopt
import getpass
import json
import requests

ok = 0
warning = 1
critical = 2
unknown = 3

progname = os.path.basename(__file__)
output_file = None

try:
    opts, args = getopt.getopt(sys.argv[1:], "o:", ["output-file="])
except getopt.GetoptError as err:
    print str(err)
    usage()
    raise SystemExit(critical)

for (opt, arg) in opts:
    if opt in ("-o", "--output-file"):
        output_file = arg
    else:
        assert False, "Unhandled option: {}".format(opt)

print "Output file: {0}".format(output_file)

if not output_file:
    print """Please specify an output file using the -o flag"""
    raise SystemExit(critical)

website = "nesi.zendesk.com"
headers = { 'Content-Type' : 'application/json' }
preferred_locale = "en-gb"

print "This script requires that you have a so-called default password for Zendesk"
print "(i.e., a different password than your single sign-on password through Tuakiri)."
print "If you do not have such a password or have forgotten it, please visit:"
print ""
print "      https://{0}/access/help".format(website)
print ""
zdmyusername = raw_input("Please enter your Zendesk primary email address: ")
zdmypassword = getpass.getpass("Please enter your Zendesk default password: ")

all_categories = []
main_categories_url = "https://{0}/api/v2/help_center/{1}/categories.json".format(website, preferred_locale)
categories_url = main_categories_url
while categories_url:
    categories_page_content = requests.get(categories_url, auth=(zdmyusername, zdmypassword)).json()
    for category in categories_page_content['categories']:
        all_categories.append(category)
    categories_url = categories_page_content['next_page']

all_sections = []
main_sections_url = "https://{0}/api/v2/help_center/{1}/sections.json".format(website, preferred_locale)
sections_url = main_sections_url
while sections_url:
    sections_page_content = requests.get(sections_url, auth=(zdmyusername, zdmypassword)).json()
    for section in sections_page_content['sections']:
        all_sections.append(section)
    sections_url = sections_page_content['next_page']

with open(output_file, 'w') as output_fh:
    for section in all_sections:

        category_name = ''
    
        for category in all_categories:
            if category['id'] == section['category_id']:
                category_name = category['name']
                break
            else:
                continue

        output_fh.write("{0}/{1}\n".format(category_name,section['name']))
